name = "bbb-site"
main = "index.js"
account_id = "01dbfaa23813de0ed498516365ee24eb"
workers_dev = true

# Configure the static site handler. By pointing `bucket` at the current
# directory the worker will be able to serve the HTML, CSS and JS files that
# already live at the root of the repository.
[site]
bucket = "."